spring.application.name=RPC
server.port=8081
# ??????????
remote.service.host=172.31.14.229
remote.service.port=9000
rpc.connection.pool.size=10
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB