apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpc-image-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-rpc
  template:
    metadata:
      labels:
        app: image-rpc
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: processor
        image: swr.cn-south-1.myhuaweicloud.com/lmy_rpc/image-processor:v2.2
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        env:
        - name: LD_LIBRARY_PATH
          value: "/app/lib"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "2000m"
---
apiVersion: v1
kind: Service
metadata:
  name: rpc-service
  namespace: default
  annotations:
    #Prometheus不抓取这个Service
    prometheus.io/scrape: "false"
spec:
  # 如果LoadBalancer一直pending，可以改为NodePort
  type: LoadBalancer
  # type: NodePort 
  # externalTrafficPolicy: Local
  selector:
    app: image-rpc
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      # nodePort: 30900